### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by gmaclennan** [appium/node-adb-client#16]
I have been trying to get this working on Mac OSX (10.11.4). I have `libusb` version `1.0.20` installed via homebrew. On the command line just using the `node-usb` library I can find my device and `open()` with no error. However, if I try running an example:

```sh
$ node ./build/lib/examples/shell.js

Starting.
Trying to find a usb device
Found an ADB device

/Users/gregor/Dev/vendor/node-adb-client/node_modules/usb/usb.js:49
		return this._configDescriptor || (this._configDescriptor = this.__getConfigDescriptor())
                                                                  ^
Error: LIBUSB_ERROR_NOT_FOUND
    at Error (native)
    at Device.Object.defineProperty.get (/Users/gregor/Dev/vendor/node-adb-client/node_modules/usb/usb.js:49:67)
    at Device.usb.Device.open (/Users/gregor/Dev/vendor/node-adb-client/node_modules/usb/usb.js:36:16)
    at Function.getAdbInterface (adb.js:66:12)
    at Function.findAdbDevices$ (adb.js:50:34)
[snip]
```

Similarly running the e2e tests fails (I have struggled with how to debug and test on my machine because I don't really know how to run the code with the same babel config as the gulp tasks, which is defined in a separate module, and does not run the end to end tests it seems with `npm test`).

```sh
$ ./node_modules/.bin/mocha build/test/functional/adb-e2e-specs.js 

1) adb-e2e "before all" hook: callee$1$0:
     Error: LIBUSB_ERROR_NOT_FOUND
      at Error (native)
      at Device.Object.defineProperty.get (node_modules/usb/usb.js:49:67)
      at Device.usb.Device.open (node_modules/usb/usb.js:36:16)
      at Function.getAdbInterface (adb.js:66:12)
      at Function.findAdbDevices$ (adb.js:50:34)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:88:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:341:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:121:21)
      at GeneratorFunctionPrototype.invoke (node_modules/babel-runtime/regenerator/runtime.js:161:37)
      at run (node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:22)
      at node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:102:28
      at flush (node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)

  2) adb-e2e "after all" hook: callee$1$0:
     TypeError: Cannot read property 'closeConnection' of null
      at Object.callee$1$0$ (test/functional/adb-e2e-specs.js:29:16)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:88:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:341:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:121:21)
      at invoke (node_modules/babel-runtime/regenerator/runtime.js:161:37)
      at callInvokeWithMethodAndArg (node_modules/babel-runtime/regenerator/runtime.js:195:16)
      at previousPromise (node_modules/babel-runtime/regenerator/runtime.js:215:17)
      at new Promise (node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:193:7)
      at AsyncIterator.enqueue (node_modules/babel-runtime/regenerator/runtime.js:214:37)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:121:21)
      at Object.runtime.async (node_modules/babel-runtime/regenerator/runtime.js:233:12)
      at Context.callee$1$0 (test/functional/adb-e2e-specs.js:28:9)
```

Due to the usage of async functions I've been finding it very hard to debug and figure out exactly where the error is coming from.

**Comment by cstyan** [comment]
Hi @gmaclennan, I'm using OSX and the same version of `libusb`. I'm assuming your device has USB debugging turned on?

Can you give a bit more info? What node version are you using.

**Comment by gmaclennan** [comment]
node v5.8.0. Further testing here, with `node-usb`. I get 8 devices back from `usb.getDeviceList()`. 7 of them `open()` with no error, but the last throws the same `LIBUSB_ERROR_NOT_FOUND` error. It is:

```
Device {
  busNumber: 20,
  deviceAddress: 0,
  deviceDescriptor: 
   { bLength: 18,
     bDescriptorType: 1,
     bcdUSB: 256,
     bDeviceClass: 9,
     bDeviceSubClass: 255,
     bDeviceProtocol: 0,
     bMaxPacketSize0: 8,
     idVendor: 1452,
     idProduct: 32773,
     bcdDevice: 408,
     iManufacturer: 0,
     iProduct: 0,
     iSerialNumber: 0,
     bNumConfigurations: 1 },
  portNumbers: [],
  interfaces: [] }
```

From what I can find this is an Apple 'OHCI Root Hub Simulation'.

**Comment by gmaclennan** [comment]
A little further investigation. I have a MacBook Pro 15" 2015. I disconnected my keyboard and mouse and removed an SD card, so no connected devices. The device listed above is still there, and it's not in my system report. I also checked network preferences and removed an iPhone USB network connection, which removed one of the USB devices, but not this one. It looks like the code is trying to call `open()` on all devices, not only ones that match `USB_VENDOR_IDS` so maybe that is why I'm getting the error?

**Comment by gmaclennan** [comment]
I was trying to use `node-debug` to find which device it was trying to open when it threw the error, but could not track it down in all the async code.

**Comment by cstyan** [comment]
@gmaclennan Hmm, I'm guessing that's some kind of bridged USB controllers on the Macbook motherboard. I heard they bridged the USB connection for the trackpad and keyboard on newer Macbooks but haven't been able to confirm.

Anyways, I've never had this error thrown for any of the USB devices the code picks up on my machine. You're right that `open()` is called on all devices, as we can't access any other functionality on a device without calling `open()`.

Do you mind trying the examples in the branch `callum-update-examples`? The examples in master haven't been updated since the rewrite. Let me know if that works. If not I'll get started on a fix, I think calling `open()` on devices that don't match any of the `USB_VENDOR_IDS` is a bug.

**Comment by gmaclennan** [comment]
I was actually using the branch `callum-update-examples`.

**Comment by cstyan** [comment]
Good to know, thanks! I'll push a branch with a potential fix quickly and ping you.

**Comment by cstyan** [comment]
@gmaclennan do you mind trying the branch `callum-issue16`, `device.open()` should no longer be called if a device's vendor ID is not one `node-adb-client` recognizes.

BTW you can run the tests via `gulp unit-test`, `gulp e2e-test`, or `gulp test`.

**Comment by gmaclennan** [comment]
Yes, that is working now, thanks!

**Comment by cstyan** [comment]
Good to hear! I'll get the fixed pushed to master in a few days.

**Comment by gmaclennan** [comment]
Thanks for this and the gulp commands. Is there a gulp task for watching without running tests every time? `npm run watch` re-runs the tests every file save so it is slow. What do you use during development?

**Comment by cstyan** [comment]
I generally run `gulp watch` while developing, I want to be sure everything still builds and passes tests with the types of changes I'm generally making. Watch also runs the task to build the bindings to ADB's crypto library, and you wouldn't be able to connect to an Android device without it. 

However, you can run any of the tasks run by `watch` independently, such as `jshint`, `lint`, `transpile`, etc.
